---
- name: Users and Group Creations 
  hosts: ics 
  become: true
  vars:
    user_name: 'weblogic'
  roles:
  - ics-user-group-create
    

- name: cus users and group creation
  hosts: cus 
  become: true
  roles:
  - ics-user-group-create

- name: Install Java
  hosts: ics 
  become: true
  roles:
  - ics-java-install

- name: Install WebLogic server	
  hosts: ics 
  become: true
  roles:
  - ics-webLogic-install
