---
- name: Create wls 10.x and 10.3.x domains
  hosts: alsb 
  sudo: True
#  vars_files:
    # User defined variables for infrastructure
#    - group_vars/infra-vars.yml
##    - wls-vars.yml
#    - group_vars/secrets.yml
  roles:
    - role: ics-wlsbasedomain-create
#    - role: ics-wlsmangedserver-create
  pre_tasks:
    # ==> Fix hosts file. Remove hostname from local loop. A workaround for vagrant
    # adding hostname to remote ip 
    - name: fix host file 192.168.0.89 entry
#      lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4' owner=root group=root mode=0644
      lineinfile: dest=/etc/hosts line='192.168.0.89 alsbhost' owner=root group=root mode=0644
