---
#==> Create new domain
- include: create_new_domain.yml
#  when: java_home_exists.stat.exists|bool == false and java_family == 'jdk'

# ==> Copy boot.properties file to Admin Server security 
- include: copy_bootproperites.yml

# ==> Create Environment Variables for Oracle user
- include: set_env_var.yml
  
