---

- name: Create user group(s)
  group:
    name: "{{ item }}"
    state: present 
  with_items: "{{ user_groups }}"
#  when: user_groups

- name: Create user
  user:
    generate_ssh_key: "{{ user_generate_ssh_key }}"
#    groups: "{{ user_groups }}"
#    append: true
    group: "{{ user_groups }}"
    name: "{{ user_name }}"
    shell: "{{ user_shell }}"

