- name: validate oracle weblogic is installed
  stat: path="{{ weblogic_home }}"
  register: wls_home

- debug:
    msg: "oracle weblogic is already installed in this {{ bea_home }}"
  when: wls_home.stat.exists

- set_fact:
    oracle_weblogic_already_installed: true
  when: wls_home.stat.exists

